#!/usr/bin/env bash
# Installs firewall; block all incoming except 22, 443, 80

# install ufw, support both IPv4 and IPv6, and ensure default values
sudo apt-get -y install ufw
sudo ufw default deny incoming

# configure
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# start
sudo ufw enable
